---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: basta
  namespace: basta
spec:
  interval: 1m
  chart:
    spec:
      version: 0.1.0
  values:
    image:
      tag: space
