apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: ingress
        namespace: ingress
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 2
      priorityClassName: system-cluster-critical
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
      service:
        type: LoadBalancer
