apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: basta
  namespace: basta
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/basta
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/basta/values.yaml
